version: 0.2

phases:
    install:
        commands:
            - echo "Node JS is installing......"
            - curl -sL https://deb.nodesource.com/setup_12.x | -E bash -
            - apt install -y nodejs
    pre_build:
        commands:
            - echo "Installing Dependencies...."
            - npm install
    build:
        commands:
            - echo "building the project"
            - npm run build